apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker-tls
spec:
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    # messageMigration requires 2+ brokers
    messageMigration: true
    enableMetricsPlugin: true
  console:
    expose: true
  acceptors:
    - bindToAllInterfaces: true
      expose: true
      name: all
      protocols: all
      sslEnabled: true
      sslSecret: my-tls-secret